### ISSUE TITLE
gen_wts_trts.py cannot found

### ISSUE THREAD

**Issue by futureflsl** [QIANXUNZDL123/tensorrtx-yolov7#1]
can you supply it?

**Comment by QIANXUNZDL123** [comment]
> can you supply it?

Now  , you download gen_wts_trtx.py

**Comment by futureflsl** [comment]
> > can you supply it?
> 
> Now , you download gen_wts_trtx.py

I found gen_wts.py at https://github.com/Carnon/trt_yolov7 ,and it work well

**Comment by QIANXUNZDL123** [comment]
> > > can you supply it?
> > 
> > 
> > Now , you download gen_wts_trtx.py
> 
> I found gen_wts.py at https://github.com/Carnon/trt_yolov7 ,and it work well

no,  https://github.com/Carnon/trt_yolov7 gen_wts.py has not anchor box vaule  so if use gen_wts.pt to wts   you well get some error
