### ISSUE TITLE
CMakeLists can help someone

### ISSUE THREAD

**Issue by futureflsl** [QIANXUNZDL123/tensorrtx-yolov7#2]
cmake_minimum_required(VERSION 2.6)

project(yolov7)

add_definitions(-std=c++11)
add_definitions(-DAPI_EXPORTS)
option(CUDA_USE_STATIC_CUDA_RUNTIME OFF)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_BUILD_TYPE Debug)

find_package(CUDA REQUIRED)

if(WIN32)
enable_language(CUDA)
endif(WIN32)

include_directories(${PROJECT_SOURCE_DIR})

include_directories(/usr/local/cuda/include)
link_directories(/usr/local/cuda/lib64)
include_directories(/firc/hdd/TensorRT-7.0.0.11/include)
link_directories(/firc/hdd/TensorRT-7.0.0.11/lib)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Ofast -g -Wfatal-errors -D_MWAITXINTRIN_H_INCLUDED")
cuda_add_library(myplugins SHARED yololayer.cu)
target_link_libraries(myplugins nvinfer cudart)

find_package(OpenCV)
include_directories(${OpenCV_INCLUDE_DIRS})

cuda_add_executable(yolov7 calibrator.cpp yolov5T.cpp preprocess.cu)

target_link_libraries(yolov7 nvinfer)
target_link_libraries(yolov7 cudart)
target_link_libraries(yolov7 myplugins)
target_link_libraries(yolov7 ${OpenCV_LIBS})

if(UNIX)
add_definitions(-O2 -pthread)
endif(UNIX)

**Comment by QIANXUNZDL123** [comment]
> cmake_minimum_required(VERSION 2.6)
> 
> project(yolov7)
> 
> add_definitions(-std=c++11) add_definitions(-DAPI_EXPORTS) option(CUDA_USE_STATIC_CUDA_RUNTIME OFF) set(CMAKE_CXX_STANDARD 11) set(CMAKE_BUILD_TYPE Debug)
> 
> find_package(CUDA REQUIRED)
> 
> if(WIN32) enable_language(CUDA) endif(WIN32)
> 
> include_directories(${PROJECT_SOURCE_DIR})
> 
> include_directories(/usr/local/cuda/include) link_directories(/usr/local/cuda/lib64) include_directories(/firc/hdd/TensorRT-7.0.0.11/include) link_directories(/firc/hdd/TensorRT-7.0.0.11/lib) set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Ofast -g -Wfatal-errors -D_MWAITXINTRIN_H_INCLUDED") cuda_add_library(myplugins SHARED yololayer.cu) target_link_libraries(myplugins nvinfer cudart)
> 
> find_package(OpenCV) include_directories(${OpenCV_INCLUDE_DIRS})
> 
> cuda_add_executable(yolov7 calibrator.cpp yolov5T.cpp preprocess.cu)
> 
> target_link_libraries(yolov7 nvinfer) target_link_libraries(yolov7 cudart) target_link_libraries(yolov7 myplugins) target_link_libraries(yolov7 ${OpenCV_LIBS})
> 
> if(UNIX) add_definitions(-O2 -pthread) endif(UNIX)

very  good ,

**Comment by futureflsl** [comment]
I successfully run this project and found this project quite well,thanks
