### ISSUE TITLE
yolov7模型转换报错

### ISSUE THREAD

**Issue by tanggt** [QIANXUNZDL123/tensorrtx-yolov7#4]
编译成功-s转换报错，一直没查出问题，想请教一下
Loading weights: ./yolov7/yolov7-trtx.wts
./yolov7/yolov7-trtx.wts
[09/17/2022-15:37:56] [E] [TRT] Parameter check failed at: Network.cpp::nvinfer1::Network::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)

**Comment by QIANXUNZDL123** [comment]
> 编译成功-s转换报错，一直没查出问题，想请教一下 Loading weights: ./yolov7/yolov7-trtx.wts ./yolov7/yolov7-trtx.wts [09/17/2022-15:37:56] [E] [TRT] Parameter check failed at: Network.cpp::nvinfer1::Network::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)

参数没对上，检查下是否模型是否对应上  lable 数量是否改了 以及图像尺寸是否修改了
